### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by Heng14** [byaman14/ZS-SSL#1]
Hi Burhaneddin,

It is really a nice job. I use your code and train on my data. The result is perfect but it seems to take a long time to train (in my case, ~10 hours for 100 epochs). Does this make sense to you or something is wrong when I am training?
Thank you so much for your help!

Best,
Heng

**Comment by byaman14** [comment]
Hi, 

Glad to hear it worked well on your data. Running time shouldn't take such a long time. I  suspect your training was done on a CPU rather than a GPU. Please make sure that you are using a  GPU, i.e. training line 14
```
os.environ["CUDA_VISIBLE_DEVICES"] = "2" #set it to available GPU
```  
The above code uses the 3rd GPU on a multi-gpu server.
Users should edit that based on the device they have. If you have a single GPU on your device you should set that number to "0". While running your code you can check if it uses the GPU. Please let me know if this helps.

**Comment by Heng14** [comment]
Hi Burhaneddin,

Thank you so much for your reply! I think I change this according to my machine and I check the gpu which shows it is running. I assume it is using gpu on my machine. Could you please tell me how long it takes on your machine when training? 
Thank you so much!

**Comment by Heng14** [comment]
Also I suspect it is related to the version of tensorflow. Could you please tell me your tensorflow version?
Thank you!

**Comment by Heng14** [comment]
Hi Burhaneddin,

I think I know what the problem is. I use tf2 and import tensorflow.compat.v1 as tf with tf.disable_v2_behavior(). It seems this way it cannot use gpu correctly. Now I install tf1.15 directly and it seems ok. Now it costs ~20s per epoch. 
Thank you!

**Comment by byaman14** [comment]
Glad to hear it is resolved! 
For your reference:
-we have provided the running times on a multi-gpu server in our paper(please see Table 2 in the paper https://openreview.net/pdf?id=085y6YPaYjP).  
-We use TF 1.13. When using our codes, I suggest using our environment to avoid the potential mismatches between versions. 
```
conda env create -f environment.yml
```

**Comment by Heng14** [comment]
Thank you so much! It takes ~640s using a multi-gpu server according to your paper. Do you use all of the 4 GPU when training?

**Comment by byaman14** [comment]
Yes, times we report is based on our multi-gpu setting. The codes we provide uses a single GPU. Users can modify the codes to incorporate the TF multi-gpu setting to run on more than 1 GPU.

**Comment by Heng14** [comment]
I see. It makes sense! Thank you so much for your help!
