### ISSUE TITLE
data preprocess

### ISSUE THREAD

**Issue by chke097** [byaman14/ZS-SSL#2]
Hello, could you share something about the processing of the dataset? Thank you!

**Comment by byaman14** [comment]
Hi, 
As a preprocessing, we normalize k-space to 0-1 region, and sensitivity maps are generated with the ESPIRIT method. Please check the readme file (last paragraph in 'how to use' section) for instructions on padding the training mask.

**Comment by byaman14** [comment]
Closing the issue
